- mkdocs.yml
This removes the non-functional 'edit on github' button at the top right of each page.
Full documentation at https://www.mkdocs.org/user-guide/configuration/#edit_uri , specifically `If you do not want any "edit URL link" displayed on your pages, then set edit_uri to an empty string to disable the automatic setting.`
If we ever want the button back, we'll want to set `edit_uri` to point at `main` instead of the default of `master` to make it functional.
> disable 'edit on github' button option for all pages

- mkdocs.yml
Our sitemap and canonical urls in page headers will refer for `hyp3-docs.asf.alaska.edu` instead of `asfhyp3.github.io`
> Update site URL for analytics

- mkdocs.yml
MkDocs enables search by default if `plugins:` is empty in `mkdocs.yml`, but must be explicitly enabled otherwise.
> Add search bar

- .github/workflows/update_sdk_version.yml
`update_sdk_version.yml` will now also bump the SDK version `conda-env.yml`
Also, minor tweaks to the git config:
* Doesn't need to be global
* Keeps style in-line with the rest of our CI/CD ymls, e.g.:
https://github.com/ASFHyP3/hyp3/blob/877e38cd491ddbcf19142b2566eca8db15e8a627/.github/workflows/deploy.yml#L112-L113
fixes #31
> Also bump SDK version in conda-env.yml

- .github/workflows/update_asf_tools_version.yml
- conda-env.yml
- docs/tools/asf_tools.md
- docs/tools/asf_tools_api.md
- docs/using/sdk.md
- docs/using/sdk_api.md
- mkdocs.yml
* auto-generates `asf_tools` API reference
* Pins the `asf_tools` version and adds a version bumping workflow (like SDK)
Also:
* Reorgs the menus to have section headers *with* content via `mkdocs-section-index`
While not required for this merge, upon the next release of `asf_tools` and `hyp3_sdk` we'll see some improvements in both of those tools documentations:
* ASFHyP3/asf-tools#69
* ASFHyP3/hyp3-sdk#58
* fixes #38
> ASF Tools and menus 

- conda-env.yml
[Update mkdocs-asf-theme to 0.2.1+](https://github.com/ASFHyP3/mkdocs-asf-theme/blob/develop/CHANGELOG.md#021)
Fixes dynamic copyright year eating page
> Update mkdocs-asf-theme to 0.2.1+

- docs/using/sdk_example.md
- mkdocs.yml
This uses [Jupyter NBViewer](https://nbviewer.jupyter.org) in an `iframe` to get a static view of the notebook inside our documentation, which can also be launched on [binder]( https://mybinder.org) (binder badge in notebook). 
* GitHub view of the notebook: https://github.com/ASFHyP3/hyp3-sdk/blob/main/docs/sdk_example.ipynb
* NBViewer of this branch: https://nbviewer.jupyter.org/github/ASFHyP3/hyp3-sdk/blob/main/docs/sdk_example.ipynb
* Binder of this branch: https://mybinder.org/v2/gh/ASFHyP3/hyp3-sdk/main?filepath=docs%2Fsdk_example.ipynb
* There are at least 3 different MkDocs plugins that convert a notebook to HTML for rendering, and I played with all three of them. I ended up not liking any of them because they lose the look and feel of a Jupyter notebook without adding custom CSS, …
> Add SDK example notebook

- .github/workflows/deploy_to_github_io.yml
Remove the CNAME file from the dev site so we don't get GitHub Pages warnings like:
Also, add force option to deploy [as recommended](https://squidfunk.github.io/mkdocs-material/publishing-your-site/) by our base theme
> Moar dev deploy fixes

- mkdocs.yml
Current pdf link: https://hyp3-docs.asf.alaska.edu/guides/Sentinel_RTC_Product_Guide.pdf
Watch the redirect in the dev site: https://hyp3-docs.asf.alaska.edu/hyp3-docs/guides/Sentinel_RTC_Product_Guide.pdf
> Add redirect for removed RTC product guide PDF

- .github/workflows/static-analysis.yml
This should make is so  trufflehog will stop complaining, and will actually only look back to the last release
> Fix trufflehog last tag export

- docs/guides/insar_product_guide.md
In the error section, we mention that it is possible to apply an atmospheric correction to the data. This change clarifies that we do not offer any of those corrections as part of the On Demand processing. 
It would be great if we could link to other software that can be used to perform these corrections on the GAMMA-generated products. Is it appropriate to add in links to GACOS http://www.gacos.net/ or TRAIN http://davidbekaert.com/download/TRAIN_manual.pdf 
I would LOVE to have a workflow or guidance that walks though using the HyP3 InSAR products in an atmospheric correction workflow.
> Clarify that we do not offer atmospheric correction options

- docs/guides/insar_product_guide.md
This PR addresses two of the conversations in the insar-guide PR:
- removes the equation and figure illustrating using InSAR for topographic mapping
- edits the critical baseline aside to differentiate between topographic and deformation mapping baseline considerations
> Remove equation and figures for DEM processing applications

- docs/products.md
This PR adds links for the RTC and InSAR On Demand story maps to the Products page.
Alternatively (or in addition?), links could be added under each product type once the docs are reorganized.
> Add links for the story maps to the Products page

- CHANGELOG.md
- docs/products.md
- docs/usage_guidelines.md
- mkdocs.yml
Turns out this doesn't require implementing any redirects, since page URLs are ultimately based on the directory structure, not the table of contents.
That said, the directory structure in the repository doesn't particularly mimic the table of contents now.  It would be nice if the two were aligned, but I'm fine leaving things how they are for now, since moving/renaming files means implementing redirects.
> Re-organize table of contents

- docs/dems.md
We updated the product header for autoRIFT when it was included in vertex and dropped the API/SDK only bits. 
Found this by using https://validator.w3.org/checklink on our test site and it was the only link that needed to be changed.
> Update autoRIFT anchor in link on DEM page

- docs/guides/insar_product_guide.md
- docs/guides/rtc_product_guide.md
Streamline table in RTC product guide, and clarify the difference between the .tif.xml and .png.xml files the tables in both product guides.
> Update metadata tables in InSAR and RTC Product Guides

- CHANGELOG.md
- docs/guides/insar_product_guide.md
This PR adjusts the InSAR Product Guide to include documentation of the water mask GeoTIFF added to the product package.
References to the water mask being applied to the phase unwrapping process have been removed (in one commit) for the time being, and can be added back in once that option is ready for release.
> Water mask documentation

- CHANGELOG.md
- docs/guides/insar_product_guide.md
This updates the mask description in the InSAR product guide to include large inland waterbodies. The changelog was modified to include it in the same patch release as the ellipsoidal incidence angle updates, so a bumpless label was applied to the PR.
> Update water mask description in InSAR PG to include large inland waterbodies

- CHANGELOG.md
- docs/guides/insar_product_guide.md
The message box announcing the availability of the water mask did not specify that it is currently only available in the SDK. 
Added clarifying language to the announcement. 
@jhkennedy or @asjohnston-asf Does this require a change in the patch number? Or can we release a bumpless change for this through to production?
> Change water masking announcement to be sdk-specific

- CHANGELOG.md
- docs/guides/insar_product_guide.md
The figures in the InSAR product guide are incorrectly attributed. This PR corrects the first one.
> Correct figure attribution in InSAR product guide

- CHANGELOG.md
- docs/using/subscriptions.md
Vertex has added documentation for subscriptions. 
This PR adds references to the hyp3-docs subscription document linking to that documentation.
> Add references to Vertex subscription documentation

- CHANGELOG.md
- environment.yml
MkDocs versions <=1.2.3 rely on a depreciated Jina2 method that was removed in Jinja2 v3.1. MkDocs v1.2.4+ is fully compatible with Jina2 3.1 and maintains backwards compatibility with older Jinja2 versions. 
The removed the temporary Jinja2 constraint and adds the correct MkDocs constraint.
> Update mkdocs dependency for jina2 bug

- CHANGELOG.md
- docs/guides/insar_product_guide.md
Also added in changes to the InSAR Product Guide that clarify that the sign convention used for the unwrapped phase is opposite to what is used for the displacement maps.
> Add documentation link for MCF phase unwrapping algorithm

- CHANGELOG.md
- docs/tutorials.md
- mkdocs.yml
The landing page is needed to easily link to our tutorials on the hyp3-docs site. I also added a super quick link to the MintPy tutorial, which I've suggested we use in  ASFHyP3/hyp3-lib#264
> Add tutorials landing page and easy MintPy tutorial link

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
I've confirmed this link doesn't appear anywhere besides the RTC product guide.
> fix broken 'get started' link in rtc product guide

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
This PR adds a section on RTC pixel spacing options to the Product Guide. It also adds pixel spacing to the default settings table.
> Add pixel spacing information to RTC Product Guide

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
- docs/products.md
This PR adds banners announcing the new options available for RTC processing to the RTC Product Guide, and corrects some text that previously omitted references to 10m and dB options.
> Add information about new RTC options

- docs/guides/rtc_product_guide.md
This PR adds clarification to the announcement boxes that the 20-m option is currently available through the HyP3 API and SDK, but not yet in Vertex
> Clarify that the 20-m product is not yet available through Vertex

- .github/workflows/check-links.yml
Temporarily disables the link checker until https://github.com/ASFHyP3/hyp3-docs/issues/340 is fixed.
> Disable link checker

- mkdocs.yml
The NASA Earthdata tophat (black bar at top :point_down:) pulls in css/java on page refresh
When using `navigation.instant`, internal pages don't refresh so it acts/performs like a "single page" site, but this prevents the tophat css/java from working, leading to a top hat that looks like:
Dropping `navigation.instant` fixes the issue. I've left it commented in the code pointing back to this issue to prevent us from enabling it again.
> remove navigation.instant to fix nasa tophat

- CHANGELOG.md
- mkdocs.yml
Google Analytics 360 is no longer set by default in `mkdocs-asf-theme` as mkdocs and mkdocs-material only support Google Analytics 4 now, so this sets it up directly here.
Follow on work is captured in #372
> Setup analyics in site since it's no longer supported in the asf-mkdocs-theme

- docs/guides/burst_insar_product_guide.md
This PR edits mentions of post-unwrapping water masking (within ISCE2 Burst Products) to reflect the fact that the water masking is now done pre-unwrapping.
> Pre-unwrapping Water Masking Documentation

- CHANGELOG.md
- docs/guides/insar_product_guide.md
This PR adds a warning box to the InSAR Product Guide alerting users to the fact that connected components files are not generated when using the GAMMA MCF algorithm for phase unwrapping. Related information is added in a couple of other relevant locations in the product guide.
> Add message about connected components file

- .github/dictionary.txt
- CHANGELOG.md
- docs/guides/gunw_product_guide.md
- docs/products.md
Once the RAiDER update has been implemented, this PR can be used to remove the warning message about ARIA GUNW On Demand not being available over Alaska. 
The changelog/version may need to be amended, depending on the timing of this release relative to other updates.
> Remove warning message about ARIA GUNW On Demand availability over Alaska

- CHANGELOG.md
- docs/using/credits.md
Due to a performance fix in https://github.com/ASFHyP3/hyp3-autorift/pull/364, we can reduce the credits back to the previous value of 25.
> Reduce autoRIFT credits
