ASFHyP3/hyp3-docs

- docs/plugins.md
Some edits/changes to the plugin docs.
> Plugin changes

- docs/getting_started.md
More suggestions.  Piecemeal acceptance is fine.
> revisions for getting_started.md

- docs/index.md
just musing at this point, feel free to accept/reject piecemeal changes
> index.md language and styling revisions

- docs/README.md
Address missed feedback in #35
* fixes missing apostrophe
* Clarifies terminal capture warning
> Address missed feedback in #35

- conda-env.yml
- mkdocs.yml
This removes some customization that has been directly incorporated into [`mkdocs-asf-theme` v0.2](https://github.com/ASFHyP3/asf-mkdocs-theme/blob/develop/CHANGELOG.md#020)
Fixes #43
> Use `mkdocs-asf-theme` v0.2

- .github/workflows/deploy_to_github_io.yml
- .github/workflows/test-and-build.yml
> Move (and fix) deployment of test website

- .github/workflows/deploy_to_github_io.yml
- environment.yml
> Pull in latest theme and setup dev site url correctly

- .github/workflows/update_asf_tools_version.yml
- .github/workflows/update_sdk_version.yml
These should probably auto-update CHANGELOG.md, too
> fix typo in hyp3_sdk, asf_tools version update workflows

- docs/using/api.md
> add documentation for job truncation

- docs/guides/rtc_product_guide.md
> update image mouse-over text to match figure labels

- docs/guides/rtc_product_guide.md
> hyphenate glo-30 in table 1

- docs/products.md
> remove 'sdk/api only' labels for insar/autorift on products page

- docs/tools/arcgis_toolbox.md
- docs/tools/asf_tools.md
- docs/using/sdk.md
- environment.yml
- macros.py
- mkdocs.yml
> Remove gitsnippet in favor of macros

- macros.py
> add a rasie for status

- docs/guides/insar_product_guide.md
> correct typos in insar_product_guide.md

- docs/guides/sar_intro.md
> correct typos in sar_intro.md

- .github/workflows/update_asf_tools_version.yml
- .github/workflows/update_sdk_version.yml
> fix branch name typo in sdk/asf_tools workflows

- docs/guides/insar_product_guide.md
> minor revisions to insar product guide

- docs/guides/insar_product_guide.md
> Fix three typos in InSAR Product Guide

- CHANGELOG.md
> update changelog for insar product guide, introduction to sar

- docs/guides/introduction_to_sar.md
> remove headers for unfinished sections from Introduction to SAR

- docs/plugins/autoRIFT.md
- docs/plugins/gamma.md
> drop unused plugin placeholders

- CHANGELOG.md
> add more detail to changelog for 0.3.0 release

- CHANGELOG.md
- docs/contact-snippet.md
- docs/contact.md
- docs/index.md
- mkdocs.yml
Leverages the mkdocs-macros-plugin we're already using.
> Provide contact info on Home page and as a stand alone page

- CHANGELOG.md
- docs/using/api.md
> HOTFIX: InSAR API example job type

- CHANGELOG.md
- docs/guides/insar_product_guide.md
Update the announcement box in the InSAR Product Guide to reflect recent releases.
- add availability of wrapped phase, incidence angle and DEM GeoTIFFs
- continue to list the water masking as being in the works.
> Insar options update

- CHANGELOG.md
- docs/guides/insar_product_guide.md
Update the notice of available InSAR Processing Options listed in the InSAR Product Guide
> Update InSAR Processing Options

- README.md
Resolves to the latest version
**Should we also put this *in the website* somewhere?**
> DOI badge on README

- CHANGELOG.md
- docs/guides/insar_product_guide.md
> add descriptions of metadata files to insar product guide

- docs/guides/insar_product_guide.md
> Adding descriptions of the InSAR parameters

- docs/guides/insar_product_guide.md
> fix typo and word wrapping for insar parameter file

- CHANGELOG.md
- README.md
- docs/guides/insar_product_guide.md
- docs/guides/rtc_product_guide.md
> Release 0.3.5

- .github/workflows/update_asf_tools_version.yml
- .github/workflows/update_sdk_version.yml
- .gitignore
- docs/tools/asf_tools_api.md
- docs/using/sdk_api.md
> Provide version on API reference page for SDK and API

- CHANGELOG.md
- docs/index.md
- docs/whats_new.md
> Drop twitter feed on home page

- tweets/hyp3-sdk-v1.2.0.tweet
> HyP3 SDK v1.2.0 📢 Tweet

- .github/workflows/release.yml
> fix typo in release workflow

- .github/workflows/release.yml
- CHANGELOG.md
- docs/guides/insar_product_guide.md
- tweets/hyp3-v2.0.2.tweet
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release v0.3.8

- CHANGELOG.md
- docs/guides/insar_product_guide.md
Update descriptions of the incidence angle map to include both the local and ellipsoid incidence angle maps.
> Update InSAR Product Guide to include ellipsoid incidence angle map

- CHANGELOG.md
- docs/guides/insar_product_guide.md
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release v0.3.9

- CHANGELOG.md
- docs/guides/insar_product_guide.md
* patch -- Patches and bugfixes for the current version that do not break current workflows
> Release 0.3.14

- docs/guides/insar_product_guide.md
Missed this paragraph when updating content to reflect the new approach for the displacement map option.
> Additional edit to InSAR Product Guide content regarding displacement map options

- .trufflehog.txt
- docs/v2-transition.md
This will become available at `hyp3-docs.asf.alaska.edu/v2-transition`
> Transition page for v1 users

- CHANGELOG.md
- docs/using/quota.md
- mkdocs.yml
> Quota page

- CHANGELOG.md
- docs/guides/insar_product_guide.md
- docs/guides/introduction_to_sar.md
This PR corrects attributions for figures from the SAR Handbook in the Intro to SAR document
> correct the attributions for the figures in the Intro to SAR document

- CHANGELOG.md
- docs/guides/insar_product_guide.md
- docs/guides/introduction_to_sar.md
This PR updates the credits for the figures included in the InSAR Product Guide and Intro to SAR documents.
> Correct figure attributions in InSAR documentation

- CHANGELOG.md
- docs/using/quota.md
> Increase monthly job quota per user from 250 to 1,000

- CHANGELOG.md
- environment.yml
> pin pygments to v2.11.2

- .trufflehog.txt
- CHANGELOG.md
- docs/tutorials/hyp3_insar_stack_for_ts_analysis.ipynb
- mkdocs.yml
> add the notebook hyp3_insar_stack_for_ts_analysis.ipynb

- .trufflehog.txt
- CHANGELOG.md
- docs/tutorials/hyp3_insar_stack_for_ts_analysis.ipynb
- mkdocs.yml
> add the tutorial notebook hyp3_insar_stack_for_ts_analysis.ipynb to main

- CHANGELOG.md
- CITATION.cff
This pull request creates a `CITATION.cff` file in the root directory of the repository, which will allow GitHub to create a "CITE AS" section on the readme page.
> CITATION.cff: create citation file

- CHANGELOG.md
- CITATION.cff
Add a `CITATION.cff` file to the repository to create a citation menu item that provides users with a way to cite the HyP3 framework.
Changes:
Added `CITATION.cff`
Changed `CHANGELOG.md`
* patch -- Patches and bugfixes for the current version that do not break current workflows
> Add a CITATION.cff file to the repository

- CITATION.cff
> Add Tom's ORCID

- docs/citing-snippet.md
- docs/index.md
- docs/usage_guidelines.md
- docs/using-snippet.md
- docs/using.md
- docs/using/vertex.md
- mkdocs.yml
> Minor edits

- docs/guides/insar_product_guide.md
> Minor changes to insar-product-guide

- CHANGELOG.md
- docs/tutorials.md
- docs/using/vertex.md
- mkdocs.yml
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
> Release 0.3.40 -- Tutorials landing page

- docs/index.md
Some words are hard to pronounce from spelling alone. 😉
> add Hyp3 pronunciation tip

- .github/workflows/static-analysis.yml
> switch to reusable github action for secrets analysis

- CHANGELOG.md
- mkdocs.yml
> set show_submodules: true for python api references

- CHANGELOG.md
- docs/tools/asf_tools_api.md
- docs/using/sdk_api.md
- mkdocs.yml
> only document asf_tools recursively, not hyp3_sdk

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
> Release v0.3.48

- CHANGELOG.md
- docs/using/api.md
> remove s2 E84 reference

- CHANGELOG.md
- docs/using/api.md
> Update for AUTORIFT  ESA S2 naming

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
> add decibel (d) in the rtc_product_guide.md

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
* patch -- Patches and bugfixes for the current version that do not break current workflows
> Release 0.3.53 - add decibel option

- docs/using/sdk_api.md
> Better display the SDK API reference so that it includes submodules

- CHANGELOG.md
- docs/tutorials/hyp3_insar_stack_for_ts_analysis.ipynb
> HyP3 mintpy updates

- CHANGELOG.md
- docs/tutorials/hyp3_insar_stack_for_ts_analysis.ipynb
- docs/using/sdk.md
- docs/using/sdk_api.md
- environment.yml
> Release v0.3.58: SDK v1.7.5

- CHANGELOG.md
- docs/guides/rtc_product_guide.md
- docs/products.md
This release adds information about new RTC processing options to hyp3-docs
* **patch -- Patches and bugfixes for the current version that do not break current workflows**
~- [ ] (If applicable) Updated the dependencies and indicated any downstream changes that are required~
~- [ ] Added/updated tests for these changes~
~- [ ] Have all dependencies been updated?~
~- [ ] Are the tests adequate?~
> Release 0.3.59 - Docs for new RTC options

- CHANGELOG.md
- docs/dems.md
- docs/guides/rtc_product_guide.md
> fix the reference to Copernicus DEM release version in hyp3-docs

- docs/tools/asf_tools.md
- docs/tools/asf_tools_api.md
- environment.yml
> Bump asf tools 0.5.2

- CHANGELOG.md
- docs/dems.md
- docs/guides/rtc_product_guide.md
- docs/tools/asf_tools.md
- docs/tools/asf_tools_api.md
- environment.yml
* patch -- Patches and bugfixes for the current version that do not break current workflows
> release version v0.3.63

- .github/dictionary.txt
- CHANGELOG.md
- docs/dems.md
- docs/guides/burst_insar_product_guide.md
- docs/guides/insar_product_guide.md
- docs/guides/rtc_product_guide.md
- environment.yml
- mkdocs.yml
> Release 0.6.0

- CHANGELOG.md
- docs/dems.md
- docs/guides/insar_product_guide.md
- docs/guides/rtc_product_guide.md
- docs/sentinel1.md
- docs/using/quota.md
See https://github.com/ASFHyP3/hyp3-docs/issues/375
> Fix admonitions

- CHANGELOG.md
- docs/dems.md
- docs/guides/insar_product_guide.md
- docs/guides/rtc_product_guide.md
- docs/sentinel1.md
- docs/using/quota.md
I've confirmed that admonitions are rendering correctly at the test site.
> Release v0.6.1

- .github/dictionary.txt
- CHANGELOG.md
- docs/guides/insar_product_guide.md
This PR adds documentation for the adaptive phase filter, and the options available for adjusting the parameter value when ordering InSAR products on demand.
> Release 0.6.2 - Adaptive phase filter documentation

- CHANGELOG.md
This PR adds a changelog entry for changes to the Burst Guide.
> Add Changelog Entry

- CHANGELOG.md
- docs/guides/insar_product_guide.md
This PR adjusts the language in the announcement of a customizable adaptive filter parameter to reflect that it is now available in Vertex.
> Update InSAR Product Guide with Vertex ADF parameter announcement

- CHANGELOG.md
- docs/guides/insar_product_guide.md
Changes at https://hyp3-docs.asf.alaska.edu/hyp3-docs/guides/insar_product_guide/#processing-options-and-optional-files look good.
> Release v0.6.6

- CHANGELOG.md
- docs/dems.md
- docs/guides/rtc_product_guide.md
Modify the DEM description and RTC product guide to inform users that the legacy DEM options are no longer available
> release v 0.8.2

- docs/tutorials/hyp3_isce2_burst_merge.ipynb
- Cleaned up text
- Added section for creating input products
- Made call to merge workflow a shell command
- Removed double plotting
- Plot only the relevant images
> Notebook review

- docs/using/requesting_access.md
@jtherrmann I've proposed some edits to the requesting access page language. All the other changes in the [PR](https://github.com/ASFHyP3/hyp3-docs/pull/450) look good to me.
> Proposed edits to requesting access page

- .github/workflows/check-links.yml
- CHANGELOG.md
- docs/using/requesting_access.md
- mkdocs.yml
- overrides/main.html
> Release v0.9.3

- .github/dictionary.txt
- .github/workflows/changelog.yml
- .github/workflows/check-links.yml
- .github/workflows/create-jira-issue.yml
- .github/workflows/labeled-pr.yml
- .github/workflows/release-template-comment.yml
- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tag-release.yml
- .github/workflows/update_asf_tools_version.yml
- .github/workflows/update_sdk_version.yml
- CHANGELOG.md
- mkdocs.yml
New link is live on the test website and works great
> Release v0.9.10

- .github/workflows/update_asf_tools_version.yml
- .github/workflows/update_sdk_version.yml
Demonstrated: https://github.com/ASFHyP3/hyp3-docs/pull/497
fixes #484
> Don't assign SDK and ASF Tools update PRs

- CHANGELOG.md
- docs/using/credits.md
- docs/using/vertex.md
- macros.py
> Release v0.10.0

- CHANGELOG.md
- docs/products.md
This PR provides content for all available InSAR on-demand jobs, and also overhauls some of the other sections to incorporate updates or streamline content.
> Update Products landing page to include all InSAR job types

- docs/guides/gunw_product_guide.md
- docs/guides/insar_product_guide.md
- docs/guides/insar_product_guide_template.md
- docs/guides/opera_rtc_product_guide.md
- docs/guides/rtc_product_guide.md
- docs/using/downloading.md
Addresses [this comment](https://github.com/ASFHyP3/hyp3-docs/pull/592#discussion_r2152874306) in [Release v0.10.11 PR](https://github.com/ASFHyP3/hyp3-docs/pull/592)
Also includes final edits to other content.
> Update description of ionospheric correction layer
